/**
 * GENERATED by scripts/audit-shoe-images.mjs — do not edit by hand.
 * Re-run `node scripts/audit-shoe-images.mjs` after changing files in
 * public/images/shoes/.
 *
 * Image slugs (`{brand}-{model}`, see shoeImageSlug) whose photo is shared with
 * a different shoe (or is the generic placeholder) and therefore cannot be
 * trusted to show the right model. The UI renders the branded studio frame for
 * these instead of a wrong photo.
 */
export const UNVERIFIED_SHOE_IMAGE_SLUGS: ReadonlySet<string> = new Set([
  'adidas-adizero-evo-sl-2',
  'adidas-evo-sl-atr',
  'asics-magic-speed-4',
  'brooks-hyperion-elite-4',
  'brooks-hyperion-max-3',
  'hoka-cielo-x1-3',
  'inov-8-trailfly-ultra-g-300-max',
  'mizuno-wave-inspire-21',
  'nike-pegasus-premium',
  'nike-pegasus-turbo',
  'puma-deviate-nitro-elite-3',
  'puma-fast-r-nitro-elite-3',
  'salomon-sense-ride-6',
  'salomon-ultra-glide-3',
  'saucony-endorphin-azura',
  'saucony-endorphin-pro-5',
  'saucony-endorphin-speed-5',
  'saucony-ride-19',
  'topo-athletic-cyclone-2',
  'topo-athletic-mtn-racer-3',
]);
